// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL4Co0YO2baSm7Il6oy3ndO_VIzwCYijY',
    appId: '1:351988701583:web:e5c1dff66856cf2ed013fa',
    messagingSenderId: '351988701583',
    projectId: 'todo-7ef01',
    authDomain: 'todo-7ef01.firebaseapp.com',
    storageBucket: 'todo-7ef01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAF-4WV1VyKL9En_u6-AZhtUNbUc919nE',
    appId: '1:351988701583:android:d1c67acf43e758e2d013fa',
    messagingSenderId: '351988701583',
    projectId: 'todo-7ef01',
    storageBucket: 'todo-7ef01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf9Fzw8g1AjwY5kGd8IEXBT1t7-qwPX9M',
    appId: '1:351988701583:ios:83a76d1c280f08b9d013fa',
    messagingSenderId: '351988701583',
    projectId: 'todo-7ef01',
    storageBucket: 'todo-7ef01.appspot.com',
    iosClientId: '351988701583-cctsjdvj7sh1fp72e1t9ijojv24lqmct.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf9Fzw8g1AjwY5kGd8IEXBT1t7-qwPX9M',
    appId: '1:351988701583:ios:7bf172302fc363c8d013fa',
    messagingSenderId: '351988701583',
    projectId: 'todo-7ef01',
    storageBucket: 'todo-7ef01.appspot.com',
    iosClientId: '351988701583-g0njesrbsl5j1st3nj6ieptc0mp54hv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoPractice.RunnerTests',
  );
}
